server:
  port: 7890
  servlet:
    context-path: /api

spring:
  application:
    name: botfarm
  jpa:
    open-in-view: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

cron:
  expression: "0 8 * * * *"

instagram:
  username: username
  password: password