CREATE TABLE file
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(511) NOT NULL,
    data BYTEA
);

CREATE TABLE profile
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER UNIQUE NOT NULL,
    token         VARCHAR(511)   NOT NULL,
    activity_rate DECIMAL        NOT NULL,
    reference     VARCHAR(127)
);

CREATE TABLE post
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id  INTEGER     NOT NULL,
    file_id     INTEGER,
    type        VARCHAR(63) NOT NULL,
    message     VARCHAR(4095),
    is_posted   BOOLEAN     NOT NULL DEFAULT FALSE,
    source_date BIGINT      NOT NULL,
    CONSTRAINT fk_post_profile_id
        FOREIGN KEY (profile_id)
            REFERENCES profile (id),
    CONSTRAINT fk_post_file_id
        FOREIGN KEY (file_id)
            REFERENCES file (id)
);