CREATE TABLE profile
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER UNIQUE NOT NULL,
    token         VARCHAR(511)   NOT NULL,
    activity_rate DECIMAL        NOT NULL,
    type          VARCHAR(63)    NOT NULL,
    reference     VARCHAR(127)   NOT NULL
);

CREATE TABLE post
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id  INTEGER NOT NULL,
    message     VARCHAR(4095),
    posted      BOOLEAN NOT NULL DEFAULT FALSE,
    source_date BIGINT  NOT NULL,
    likes_count INTEGER NOT NULL,
    CONSTRAINT fk_post_profile_id
        FOREIGN KEY (profile_id)
            REFERENCES profile (id)
);

CREATE TABLE file
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(511) NOT NULL,
    post_id INTEGER      NOT NULL,
    data    BYTEA,
    CONSTRAINT fk_file_post_id
        FOREIGN KEY (post_id)
            REFERENCES post (id)
);