CREATE TABLE file_info
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(127) NOT NULL,
    reference VARCHAR(511) NOT NULL
);

CREATE TABLE profile
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE post
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id  INTEGER     NOT NULL,
    file_id     INTEGER,
    type        VARCHAR(63) NOT NULL,
    message     VARCHAR(4095),
    supplied    BOOLEAN     NOT NULL DEFAULT FALSE,
    source_date TIMESTAMP   NOT NULL,
    CONSTRAINT fk_post_profile_id
        FOREIGN KEY (profile_id)
            REFERENCES profile (id),
    CONSTRAINT fk_post_file_info_id
        FOREIGN KEY (file_id)
            REFERENCES file_info (id)
);